name: todoapp
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: 
  hive_flutter:




dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

  flutter_lints: ^1.0.0
  dart_code_metrics: ^4.10.1

flutter:
  uses-material-design: true

